# Theme settings
doks:
    baseurl:
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: jjensn.com
            image: 
        # nav:
        #     - item_name: Item 1
        #       item_url: '#'
        #     - item_name: Item 2
        #       item_url: '#'
        #     - item_name: Item 3
        #       item_url: '#'
    footer:
        content:
            logo:
                text: jjensn.com
                image:
            copyright: always open for new opportunities! hire (a)t jjensn.com
        social_list:
            - network_name: github
              profile_url: 'https://github.com/jjensn'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md', 'old', 'dev.sh', 'docker-compose.yml', 'docker-entrypoint.sh', 'Dockerfile', 'old.jjensn.com', 'build.sh', 'documentation' ]
permalink: /:title/
