version: '3'

services:
  jekyll:
    container_name: jjensn.com
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - repo=https://github.com/jjensn/jjensn.com.git
        - branch=master
        - PORT=80
    environment:
      - DEPLOY_ENV=${DEPLOY_ENV}
    volumes:
      - ./site:/export 
      - ${PWD}:/development
    ports:
      - '4000:80'